// ------------------------------------------
//  Created by Jean-Michel Bruel on 2019-12.
//  Copyright (c) 2019 IRIT/U. Toulouse. All rights reserved.
// Thanks to Louis Chanoua for code & idea
// ------------------------------------------
= DUT-Info/S3/M3105 (CPOA) : Projet refactoring
Andrey Chertkov
v20.1, {localdate}
:mailto: a.chertkov@innopolis.ru
:status: bottom
:inclusion:
:experimental:
:uk:
:toc: toc2
:asciidoctorlink: link:http://asciidoctor.org/[Asciidoctor]indexterm:[Asciidoctor]

// ------------------------------------------

== How to deploy project

The application requires Python 3.8 or above

First, create a virtual environment
```
pip install virtualenv
virtualenv venv
```

To activate venv on Windows
```
venv\Scripts\activate
```

To activate venv on Linux
```
source venv/bin/activate
```

To run tests:
```
python -m unittest -v
```

To run the application:
```
python -m task_list
```

Notes on testing
----------------
For end-to-end testing, a subprocess was used instead of threading. The subprocess module allows
you to create a new process and connect to their input and output pipes. 

The application test runs main from task_list module and then injects the inputs into stdin. 
The IO Pipe is blocking which more closely emulates the real behavior of stdin when calling readline. 
The call will block until data is written to stdin. 
Likewise stdout.read will block until there is data to be read.

Because of the potential for blocking, a threaded timer was introduced 
to kill the subprocess on deadlock. The timeout is currently set to 2 seconds
but if additional tests run longer than that the timeout should be increased.

As the subprocess captures all input and output, using print statements for debugging during tests
will not work as expected. 

== Change log

1. Add deadline, feature #2
  * Refactoring:
    . Rewrite using link:https://refactoring.guru/design-patterns/command:[Command Pattern]. Before, commands sends as a string, that is link:https://refactoring.guru/smells/primitive-obsession:[Primitive Obsession]
    . Add unit tests for each command
    . Rewrite routing using mapping and recursive search for subcommands
  * Features:
    . Add `deadline <ID> <date in '%d/%m/%Y %H:%M:%S'>` command
    . Add `today` command
